name: Build and publish Watch
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore Watch
    - name: Dotnet build dll
      run: dotnet publish --configuration Release --no-restore Watch -o build
    - name: Publish action artefact
      uses: actions/upload-artifact@v2
      with:
        name: watch-artifact
        path: build/Watch.dll

    - name: Release to github
      uses: docker://antonyurchenko/git-release:latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DRAFT_RELEASE: "false"
        PRE_RELEASE: "false"
        CHANGELOG_FILE: "Watch/CHANGELOG.md"
        ALLOW_EMPTY_CHANGELOG: "true"
      with:
        args: |
            build/Watch.dll
